import { ResponseType } from './types/newsApiTypes';

export const testData: ResponseType = {
    pagination: { limit: 25, offset: 0, count: 25, total: 10000 },
    data: [
        {
            author: 'Laura Berestecki',
            title: 'Boston College Men\u2019s Hockey Outshoots Sun Devils, But Falls 2-1 in NYE Matchup',
            description:
                'Photo by Richard T Gagnon/Getty Images The Eagles and Sun Devils ended 2022 with a series split this weekend, with BC winning last night and ASU taking home the victory tonight. BC outshot ASU 43-18 tonight, but couldn\u2019t get past T.J. Semptimphelter, who finished the game with a .977 save percentage to allow ASU to split the series with a 2-1 victory.Tonight\u2019s game got off to a much slower start than last night\u2019s, and the teams went into the first intermission tied at 0. BC had a slight edge in shots on goal after 1, leading 11-8 despite Trevor Kuntar picking up a pair of penalties late...',
            url: 'https://www.bcinterruption.com/2022/12/31/23533876/boston-college-mens-hockey-outshoots-sun-devils-but-falls-2-1-in-nye-matchup',
            source: 'bcinterruption',
            image: null,
            category: 'general',
            language: 'en',
            country: 'us',
            published_at: '2023-01-01T00:19:52+00:00',
        },
        {
            author: 'Victoria Ward',
            title: 'Prince Andrew\u2019s deal with Giuffre bought one year of silence. Now the clause is about to expire',
            description:
                'Giuffre is once again likely to be free to talk about the years of abuse she suffered at the hands of Jeffrey Epstein, the convicted sex offender.',
            url: 'https://www.smh.com.au/world/europe/prince-andrew-s-deal-with-giuffre-bought-one-year-of-silence-now-the-clause-is-about-to-expire-20230101-p5c9os.html?ref=rss\u0026utm_medium=rss\u0026utm_source=rss_world',
            source: 'The Sydney Morning Herald',
            image: 'https://static.ffx.io/images/$zoom_0.3027%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_13/t_crop_custom/q_86%2Cf_jpg/f0a936fde318a2a56b5541015aa2e7793e57d6aa',
            category: 'general',
            language: 'en',
            country: 'au',
            published_at: '2023-01-01T00:13:00+00:00',
        },
        {
            author: 'Victoria Ward',
            title: 'Prince Andrew\u2019s deal with Giuffre bought one year of silence. Now the clause is about to expire',
            description:
                'Giuffre is once again likely to be free to talk about the years of abuse she suffered at the hands of Jeffrey Epstein, the convicted sex offender.',
            url: 'https://www.smh.com.au/world/europe/prince-andrew-s-deal-with-giuffre-bought-one-year-of-silence-now-the-clause-is-about-to-expire-20230101-p5c9os.html?ref=rss\u0026utm_medium=rss\u0026utm_source=rss_feed',
            source: 'The Sydney Morning Herald',
            image: 'https://static.ffx.io/images/$zoom_0.3027%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_13/t_crop_custom/q_86%2Cf_jpg/f0a936fde318a2a56b5541015aa2e7793e57d6aa',
            category: 'general',
            language: 'en',
            country: 'au',
            published_at: '2023-01-01T00:13:00+00:00',
        },
        {
            author: 'Victoria Ward',
            title: 'Prince Andrew\u2019s deal with Giuffre bought one year of silence. Now the clause is about to expire',
            description:
                'Giuffre is once again likely to be free to talk about the years of abuse she suffered at the hands of Jeffrey Epstein, the convicted sex offender.',
            url: 'https://www.watoday.com.au/world/europe/prince-andrew-s-deal-with-giuffre-bought-one-year-of-silence-now-the-clause-is-about-to-expire-20230101-p5c9os.html?ref=rss\u0026utm_medium=rss\u0026utm_source=rss_world',
            source: 'watoday',
            image: 'https://static.ffx.io/images/$zoom_0.3027%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_13/t_crop_custom/q_86%2Cf_jpg/f0a936fde318a2a56b5541015aa2e7793e57d6aa',
            category: 'general',
            language: 'en',
            country: 'au',
            published_at: '2023-01-01T00:13:00+00:00',
        },
        {
            author: 'The Canadian Press',
            title: 'B.C.\u2019s Health Minister supports COVID-19 testing for travellers from China',
            description:
                'VANCOUVER \u0026#8212; British Columbia\u0026#8217;s health minister says he supports Ottawa\u0026#8217;s decision to temporarily require people flying from China, Hong Kong and Macao to test negative for COVID-19 before leaving for Canada, beginning in early January. Adrian Dix says in a news release that the province will continue to closely monitor the COVID-19 situation around the [\u0026#8230;]',
            url: 'https://nationalpost.com/pmn/news-pmn/canada-news-pmn/b-c-s-health-minister-supports-covid-19-testing-for-travellers-from-china',
            source: 'nationalpost',
            image: null,
            category: 'general',
            language: 'en',
            country: 'us',
            published_at: '2023-01-01T00:19:44+00:00',
        },
        {
            author: 'News desk',
            title: 'KP, Balochistan witness spike in terrorist attacks during 2022',
            description:
                'The year 2022 ended with December as the deadliest month for Pakistan while the country suffered as many as 376 terror attacks in last year that resulted in an increased number of casualties in Khyber Pakhtunkhwa (KP) and Balochistan provinces. The Center for Research and Security Studies (CRSS), in its annual report released on Saturday, [\u0026#8230;]',
            url: 'https://pakobserver.net/kp-balochistan-witness-spike-in-terrorist-attacks-during-2022/?utm_source=rss\u0026utm_medium=rss\u0026utm_campaign=kp-balochistan-witness-spike-in-terrorist-attacks-during-2022',
            source: 'pakobserver',
            image: null,
            category: 'general',
            language: 'en',
            country: 'us',
            published_at: '2023-01-01T00:09:15+00:00',
        },
        {
            author: 'Spc. Jessica Silhavy',
            title: 'State command chief leads through strong support from family, fellow Airmen',
            description:
                'Profile of Chief Master Sgt. Troy R. Taylor, who became the 12th command chief master sergeant of the Ohio Air National Guard in September 2022.',
            url: 'https://www.dvidshub.net/news/436168/state-command-chief-leads-through-strong-support-family-fellow-airmen',
            source: 'dvidshub',
            image: 'https://cdn.dvidshub.net/media/thumbs/photos/2209/7465219/250x166_q75.jpg',
            category: 'general',
            language: 'en',
            country: 'us',
            published_at: '2023-01-01T00:14:35+00:00',
        },
        {
            author: null,
            title: 'Joe Biden got furious about reminders of Donald Trump in the White House',
            description:
                'A new book revealed Joe Biden was angry when he came across reminders of Donald Trump in the White House, including a $50,000 golf simulator.',
            url: 'https://www.dailymail.co.uk/news/article-11588901/Joe-Biden-got-furious-reminders-Donald-Trump-White-House.html?ns_mchannel=rss\u0026ns_campaign=1490\u0026ito=1490',
            source: 'Mail',
            image: 'https://i.dailymail.co.uk/1s/2022/12/31/23/66085433-0-image-a-17_1672528100934.jpg',
            category: 'general',
            language: 'en',
            country: 'gb',
            published_at: '2023-01-01T00:13:30+00:00',
        },
        // {
        //     author: 'Lucy Norris',
        //     title: 'Katherine Ryan would sooner take medical advice from Molly-Mae Hague than Matt Hancock',
        //     description: '\u0027Roll out the pretty little vaccine\u0027.',
        //     url: 'https://metro.co.uk/2023/01/01/katherine-ryan-would-trust-molly-mae-over-matt-hancock-with-health-18020323/',
        //     source: 'Metro',
        //     image: null,
        //     category: 'general',
        //     language: 'en',
        //     country: 'gb',
        //     published_at: '2023-01-01T00:12:51+00:00',
        // },
        // {
        //     author: 'Andrew E. Kramer and Anton Troianovski',
        //     title: 'Russia Bombards Ukraine as Putin Calls Invasion a \u2018Sacred Duty\u2019',
        //     description:
        //         'Explosions hit the capital, Kyiv, and other cities on the final day of a year shaped by Russia\u2019s invasion. Flanked by soldiers, Vladimir V. Putin called the invasion a \u201csacred duty\u201d of Russians.',
        //     url: 'https://www.nytimes.com/2022/12/31/world/europe/ukraine-strikes-russia-new-years-eve.html',
        //     source: 'nytimes',
        //     image: 'https://static01.nyt.com/images/2022/12/31/multimedia/31ukraine-ledeall-sub-1-f693/31ukraine-ledeall-sub-1-f693-moth.jpg',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:31:53+00:00',
        // },
        // {
        //     author: null,
        //     title: 'TCU topples Michigan, advances to College Football Playoff finale',
        //     description:
        //         'TCU scored on two interception returns and held off a chaotic Michigan rally to win the Fiesta Bowl, the first College Football Playoff semifinal, and clinch a spot in the title game Saturday in Glendale, Ariz.',
        //     url: 'https://www.upi.com/Sports_News/2022/12/31/TCU-topples-Michigan-College-Football-Playoff/1401672520985/',
        //     source: 'upi',
        //     image: 'https://cdnph.upi.com/ph/st/th/1401672520985/2022/upi/8f1c0e847074f711e4ac9ab0314fa57c/v1.5/TCU-topples-Michigan-advances-to-College-Football-Playoff-finale.jpg',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:33:27+00:00',
        // },
        // {
        //     author: 'Cloe Read',
        //     title: 'Rodeo rider killed in New Year\u2019s Eve tragedy',
        //     description:
        //         'The 25-year-old was competing in the Novice Bull Ride at the Warwick Show when he was thrown from the bull and suffered critical chest injuries.\u00a0',
        //     url: 'https://www.smh.com.au/national/queensland/rodeo-rider-killed-in-new-year-s-eve-tragedy-20230101-p5c9pl.html?ref=rss\u0026utm_medium=rss\u0026utm_source=rss_national',
        //     source: 'The Sydney Morning Herald',
        //     image: 'https://static.ffx.io/images/$zoom_1.4814132765819674%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_266%2C$y_203/t_crop_custom/q_86%2Cf_auto/f189f5deafc395c289c3658ae8f759e1a929c712',
        //     category: 'general',
        //     language: 'en',
        //     country: 'au',
        //     published_at: '2023-01-01T01:32:59+00:00',
        // },
        // {
        //     author: 'Pat Rooney',
        //     title: 'Late rally not enough to offset ugly effort for CU Buffs men\u2019s basketball in loss at Cal',
        //     description:
        //         'There have been plenty of ugly performances for Colorado at Cal\u2019s Haas Pavilion. None of them were uglier, or more deflating, than the effort that unfolded on Saturday.',
        //     url: 'https://www.greeleytribune.com/2022/12/31/late-rally-not-enough-to-offset-ugly-effort-for-cu-buffs-mens-basketball-in-loss-at-cal/',
        //     source: 'greeleytribune',
        //     image: 'https://www.greeleytribune.com/wp-content/uploads/2022/12/BUF-Z-CUvCAL4123122.jpg?w=1400px\u0026strip=all',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:26:57+00:00',
        // },
        // {
        //     author: 'Shweta Agnihotri',
        //     title: 'Sports Calendar 2023: Starting Australian OPEN, BIG LIVE Sporting events LINED-UP in 2023, Check complete Sports Calendar for 2023 \u0026 Follow all Sports ACTION live',
        //     description:
        //         'Sports Calendar 2023 \u0026#8211; Indian Cricket Schedule: Starting Australian OPEN T, BIG LIVE Sporting events LINED-UP in 2023, Check complete Sports Calendar\u0026#8230;The post Sports Calendar 2023: Starting Australian OPEN, BIG LIVE Sporting events LINED-UP in 2023, Check complete Sports Calendar for 2023 \u0026 Follow all Sports ACTION live first appeared on Inside Sport India.',
        //     url: 'https://www.insidesport.in/sports-calendar-2023-starting-australian-open-big-live-sporting-events-lined-up-in-2023-check-complete-sports-calendar-for-2023-follow-all-sports-action-live/',
        //     source: 'Insidesport',
        //     image: null,
        //     category: 'sports',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:27:35+00:00',
        // },
        // {
        //     author: 'Reuters',
        //     title: 'No. 3 TCU holds off No. 2 Michigan to earn championship spot',
        //     description:
        //         'TCU\u0026#8217;s defense returned two interceptions for touchdowns and quarterback Max Duggan accounted for four touchdowns Saturday as the third-ranked Horned Frogs outgunned No. 2 Michigan 51-45 in the College Football Playoff semifinals in Glendale, Ariz. Both teams are 13-1, but it\u0026#8217;s TCU that will move on to the championship game on Jan. 9 at SoFi [\u0026#8230;]',
        //     url: 'https://nationalpost.com/pmn/sports-pmn/no-3-tcu-holds-off-no-2-michigan-to-earn-championship-spot',
        //     source: 'nationalpost',
        //     image: null,
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:27:27+00:00',
        // },
        // {
        //     author: 'Adam Grosbard',
        //     title: 'USC defense keeps long-term vision for unit\u2019s progress',
        //     description:
        //         'Trojans\u0027 defense hasn\u0027t lived up to expectations, but in light of its dismal 2021 and strides made this past month, there are high hopes for the Cotton Bowl',
        //     url: 'https://www.sgvtribune.com/2022/12/31/usc-defense-keeps-long-term-vision-for-units-progress/',
        //     source: 'sgvtribune',
        //     image: 'https://www.sgvtribune.com/wp-content/uploads/2022/12/LDN-L-USC-FBC-1127-KB60.jpg?w=1400px\u0026strip=all',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:35:03+00:00',
        // },
        // {
        //     author: 'Trevor McCue, MaizeAndBlueReview.com',
        //     title: 'TCU advances to title game after defeating Michigan in wild Fiesta Bowl',
        //     description:
        //         'Max Duggan and the TCU Horned Frogs will play for a national championship.',
        //     url: 'https://michigan.rivals.com/news/three-takeaways-after-michigan-s-chaotic-loss-to-tcu-in-fiesta-bowl',
        //     source: 'Rivals',
        //     image: 'https://images.rivals.com/image/upload/f_auto,q_auto,t_hero_desktop/hgl8mj5jsykeu7ubywnh',
        //     category: 'sports',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:26:13+00:00',
        // },
        // {
        //     author: 'Spc. Jessica Silhavy',
        //     title: 'A Day in the Life: Ohio National Guard historian',
        //     description:
        //         'Profile of Sgt. 1st Class Josh Mann, who is charged with preserving the history and artifacts of the Ohio National Guard',
        //     url: 'https://www.dvidshub.net/news/436174/day-life-ohio-national-guard-historian',
        //     source: 'dvidshub',
        //     image: 'https://cdn.dvidshub.net/media/thumbs/photos/2212/7576925/250x167_q75.jpg',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:27:21+00:00',
        // },
        // {
        //     author: null,
        //     title: 'A Day in the Life: Ohio National Guard historian [Image 3 of 5]',
        //     description:
        //         'Sgt. 1st Class Joshua Mann, Ohio National Guard historian, marches in the 2015 Columbus Veterans Day Parade, with partners from the Ohio History Connection. Mann was portraying a 37th Infantry Division Soldier from World War II. (Courtesy photo)',
        //     url: 'https://www.dvidshub.net/image/7576927/day-life-ohio-national-guard-historian',
        //     source: 'dvidshub',
        //     image: 'https://cdn.dvidshub.net/media/thumbs/photos/2212/7576927/250x167_q75.jpg',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T01:28:28+00:00',
        // },
        // {
        //     author: null,
        //     title: 'Aile bir e\u011fitim yuvas\u0131d\u0131r',
        //     description:
        //         'Toplumun temelini olu\u015fturan en \u00f6nemli unsur ailedir. Aile ise evlilik ile meydana gelmektedir. \u0130slam\u2019da da evlilik oldu...',
        //     url: 'https://www.yenisafak.com/hayat/aile-bir-egitim-yuvasidir-3898933',
        //     source: 'Yeni Safak',
        //     image: 'https://img.piri.net/mnresize/500/-/resim/imagecrop/2023/01/01/04/30/resized_4ecd7-bc957803adobestock_335616831.jpg Aile bir e\u011fitim yuvas\u0131d\u0131r https://www.yenisafak.com/hayat/aile-bir-egitim-yuvasidir-3898933',
        //     category: 'general',
        //     language: 'en',
        //     country: 'tr',
        //     published_at: '2023-01-01T01:31:17+00:00',
        // },
        // {
        //     author: 'Alejandro Pena',
        //     title: 'U.S. Air Force and Army conduct airborne operations at JBER [Image 31 of 32]',
        //     description:
        //         'A U.S. Army paratrooper assigned to the 2nd Infantry Brigade Combat Team (Airborne), 11th Airborne Division, \u201cArctic Angels,\u201d recovers his jump gear after successfully completing airborne operations at Malemute Drop Zone, Joint Base Elmendorf-Richardson, Alaska, Aug. 24, 2022. Aircrew assigned to the 62nd Airlift Wing, out of Joint Base Lewis-McChord, Wash., provided air support for the training. The Arctic Angels stay proficient at their primary function of being a Joint Forcible Entry unit, able to respond and project power across the Pacific within 18 hours. (U.S. Air Force photo by...',
        //     url: 'https://www.dvidshub.net/image/7576989/us-air-force-and-army-conduct-airborne-operations-jber',
        //     source: 'dvidshub',
        //     image: 'https://cdn.dvidshub.net/media/thumbs/photos/2212/7576989/250x167_q75.jpg',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T02:43:45+00:00',
        // },
        // {
        //     author: 'Alejandro Pena',
        //     title: 'U.S. Air Force and Army conduct airborne operations at JBER [Image 30 of 32]',
        //     description:
        //         'A U.S. Army paratrooper assigned to the 2nd Infantry Brigade Combat Team (Airborne), 11th Airborne Division, \u201cArctic Angels,\u201d recovers his jump gear after successfully completing airborne operations at Malemute Drop Zone, Joint Base Elmendorf-Richardson, Alaska, Aug. 24, 2022. Aircrew assigned to the 62nd Airlift Wing, out of Joint Base Lewis-McChord, Wash., provided air support for the training. The Arctic Angels stay proficient at their primary function of being a Joint Forcible Entry unit, able to respond and project power across the Pacific within 18 hours. (U.S. Air Force photo by...',
        //     url: 'https://www.dvidshub.net/image/7576988/us-air-force-and-army-conduct-airborne-operations-jber',
        //     source: 'dvidshub',
        //     image: 'https://cdn.dvidshub.net/media/thumbs/photos/2212/7576988/250x167_q75.jpg',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T02:43:41+00:00',
        // },
        // {
        //     author: 'Alejandro Pena',
        //     title: 'U.S. Air Force and Army conduct airborne operations at JBER [Image 26 of 32]',
        //     description:
        //         'U.S. Army paratroopers assigned to the 2nd Infantry Brigade Combat Team (Airborne), 11th Airborne Division, \u201cArctic Angels,\u201d jump from a U.S. Air Force C-17 Globemaster III during airborne operations over Malemute Drop Zone at Joint Base Elmendorf-Richardson, Alaska, Aug. 24, 2022. The aircrew and aircraft were assigned to the 62nd Airlift Wing out of Joint Base Lewis-McChord, Wash. The Arctic Angels stay proficient at their primary function of being a Joint Forcible Entry unit, able to respond and project power across the Pacific within 18 hours. (U.S. Air Force photo by Alejandro Pe\u00f1a)',
        //     url: 'https://www.dvidshub.net/image/7576984/us-air-force-and-army-conduct-airborne-operations-jber',
        //     source: 'dvidshub',
        //     image: 'https://cdn.dvidshub.net/media/thumbs/photos/2212/7576984/250x167_q75.jpg',
        //     category: 'general',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-01T02:43:26+00:00',
        // },
        // {
        //     author: 'Daniel McCarthy',
        //     title: 'Pope Benedict: Defender of sacred tradition',
        //     description:
        //         'Pope Benedict XVI should not be remembered as the pontiff who resigned but as a champion of faith \u2014 against fanaticism and cold materialism alike.\u00a0',
        //     url: 'https://nypost.com/2022/12/31/pope-benedict-defender-of-sacred-tradition/',
        //     source: 'Post',
        //     image: 'https://nypost.com/wp-content/uploads/sites/2/2022/12/pope-benedict-1.jpg?quality=90\u0026strip=all',
        //     category: 'general',
        //     language: 'en',
        //     country: 'zm',
        //     published_at: '2023-01-01T02:49:08+00:00',
        // },
        // {
        //     author: 'Peter Botte',
        //     title: 'Depleted Knicks throttle Rockets to snap five-game losing streak',
        //     description:
        //         'The depleted Knicks needed to salvage at least one win following a disastrous first two games in Texas, and they ended 2022 on a positive note.',
        //     url: 'https://nypost.com/2022/12/31/knicks-throttle-rockets-to-snap-five-game-losing-streak/',
        //     source: 'Post',
        //     image: 'https://nypost.com/wp-content/uploads/sites/2/2022/12/Julius-Randle-2.jpg?quality=90\u0026strip=all',
        //     category: 'general',
        //     language: 'en',
        //     country: 'zm',
        //     published_at: '2023-01-01T02:48:48+00:00',
        // },
    ],
};

export const testCategoryData: ResponseType = {
    pagination: { limit: 25, offset: 0, count: 25, total: 244 },
    data: [
        {
            author: 'Jancee Dunn',
            title: '\u00bfC\u00f3mo mantener la felicidad todo el a\u00f1o?',
            description:
                'Al emprender este reto nos comprometimos a priorizar las relaciones y considerarlas como un componente vital de la salud general. Varios expertos que nos dieron consejos pr\u00e1cticos para este 2023.',
            url: 'https://www.nytimes.com/2023/01/10/espanol/como-ser-feliz.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/10/well/08Well-Challenge-WrapUp/08Well-Challenge-WrapUp-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-16T14:49:50+00:00',
        },
        {
            author: 'Jancee Dunn',
            title: 'Day 4: Why you should write a \u2018living eulogy\u2019',
            description: 'Happy people express their gratitude for others.',
            url: 'https://www.nytimes.com/2023/01/04/well/gratitude-letter-happiness-challenge.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/04/well/5Well-Chall-Letter/5Well-Chall-Letter-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-05T03:04:03+00:00',
        },
        {
            author: null,
            title: 'Do your vitamin and mineral supplements actually do anything? Here\u0027s what experts say.',
            description:
                'Do your vitamin and mineral supplements actually do anything? Here\u0027s what experts say.',
            url: 'https://news.yahoo.com/do-your-vitamin-and-mineral-supplements-actually-do-anything-heres-what-experts-say-155647571.html',
            source: 'Yahoo News',
            image: 'https://s.yimg.com/os/creatr-uploaded-images/2023-01/08f55fd0-8b70-11ed-aff7-513d29cdbdc1',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-03T15:56:47+00:00',
        },
        {
            author: 'Dani Blum',
            title: 'The Mediterranean Diet Really Is That Good for You. Here\u2019s Why.',
            description:
                'It has become the bedrock of virtuous eating. Experts answer common questions about how it leads to better health.',
            url: 'https://www.nytimes.com/2023/01/06/well/eat/mediterranean-diet-health.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/06/multimedia/06WELL-MEDITERRANEAN-DIET-1-eb57/06WELL-MEDITERRANEAN-DIET-1-eb57-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-06T19:53:39+00:00',
        },
        {
            author: 'Jancee Dunn',
            title: 'Day 6: Don\u2019t cancel those plans',
            description:
                'If you think you\u2019ll be happier staying home, you\u2019re wrong.',
            url: 'https://www.nytimes.com/2023/01/06/well/social-calendar-happiness-challenge.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/10/well/5Well-MakeADate/5Well-MakeADate-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-07T03:46:41+00:00',
        },
        {
            author: 'Cindy Kuzma',
            title: 'What is a Dynamic Warm-Up and What Exercises Should it Include?',
            description:
                'Instead of stretching, pick a few key moves to properly prepare your body for your workout.',
            url: 'https://www.nytimes.com/2023/01/05/well/move/dynamic-warm-up-exercises.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/05/multimedia/05Well-DynamicWarmUp-final-1-11b4/05Well-DynamicWarmUp-final-1-11b4-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-05T16:06:01+00:00',
        },
        {
            author: 'Karen Paul',
            title: 'A Web Between Her Body and Mine',
            description:
                'For decades we connected nearly every day. One terrible moment changed all that.',
            url: 'https://www.nytimes.com/2023/01/06/style/modern-love-a-web-between-her-body-and-mine.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/08/fashion/08MODERN-FRIEND/08MODERN-FRIEND-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-09T20:34:38+00:00',
        },
        {
            author: 'Sophie Egan',
            title: '10 Nutrition Myths Experts Wish Would Die',
            description:
                'We surveyed some of the country\u2019s leading authorities to reveal the truth about fat, dairy, soy and more.',
            url: 'https://www.nytimes.com/2023/01/19/well/eat/nutrition-myths.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/19/well/19NUTRITION-MYTHS/19NUTRITION-MYTHS-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-19T16:32:32+00:00',
        },
        {
            author: null,
            title: '\u0027I\u0027ve been given a do not resuscitate order but I want to live\u0027',
            description:
                'Marie McLean is scared to go to sleep after discovering her records tell medics not to attempt CPR.',
            url: 'https://www.bbc.co.uk/news/uk-scotland-glasgow-west-64334328?at_medium=RSS\u0026at_campaign=KARANGA',
            source: 'BBC News - Health',
            image: null,
            category: 'health',
            language: 'en',
            country: 'gb',
            published_at: '2023-01-21T09:20:15+00:00',
        },
        {
            author: 'Dani Blum',
            title: 'Are Saunas Good for You? What to Know About Health Benefits',
            description:
                'Sweating in small hot rooms has been a wellness staple for centuries. But don\u2019t believe everything you hear.',
            url: 'https://www.nytimes.com/2023/01/27/well/live/sauna-health-benefits.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/19/multimedia/WELL-SAUNA-HEALTH1-qlgj/WELL-SAUNA-HEALTH1-qlgj-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-27T15:10:56+00:00',
        },
        {
            author: null,
            title: 'Paramedics say people are getting ill because their homes are so cold',
            description:
                'Ambulance crews say they are treating more people who are sick because they cannot afford to heat their home.',
            url: 'https://www.bbc.co.uk/news/uk-scotland-64338770?at_medium=RSS\u0026at_campaign=KARANGA',
            source: 'BBC News - Health',
            image: null,
            category: 'health',
            language: 'en',
            country: 'gb',
            published_at: '2023-01-25T06:31:03+00:00',
        },
        {
            author: 'Helen Ouyang',
            title: 'Your Next Hospital Bed Might Be at Home',
            description:
                'In a time of strained capacity, the \u201chospital at home\u201d movement is figuring out how to create an inpatient level of care anywhere.',
            url: 'https://www.nytimes.com/2023/01/26/magazine/hospital-at-home.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/29/magazine/29mag-hospital-06/29mag-hospital-06-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-27T22:11:29+00:00',
        },
        {
            author: 'Jancee Dunn',
            title: 'The Life-Changing Magic of a Urologist',
            description:
                'Here are three issues you may want to address with a professional.',
            url: 'https://www.nytimes.com/2023/01/27/well/the-life-changing-magic-of-a-urologist.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/01/26/well/26WELL-NL-UROLOGISTS/26WELL-NL-UROLOGISTS-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-01-29T17:06:26+00:00',
        },
        {
            author: 'Jancee Dunn',
            title: 'What Times Readers Would Change About Their Doctors\u2019 Offices',
            description:
                'These small tweaks could go a long way toward improving patients\u2019 overall experience.',
            url: 'https://www.nytimes.com/2023/02/03/well/live/doctors-office-patients.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/02/02/well/02WELL-NL-DR-IDEAS/02WELL-NL-DR-IDEAS-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-02-03T15:22:25+00:00',
        },
        {
            author: 'Dani Blum',
            title: 'How a Consistent Sleep Schedule Benefits Your Health',
            description:
                'New research\u00a0affirms what doctors have long advised: Go to bed and wake up at the same time every day for big health benefits.',
            url: 'https://www.nytimes.com/2023/02/15/well/mind/sleep-schedule-heart-health.html',
            source: 'The New York Times',
            image: 'https://static01.nyt.com/images/2023/02/15/well/15WELL-SLEEP-CONSISTENCY1/15WELL-SLEEP-CONSISTENCY1-moth.jpg',
            category: 'health',
            language: 'en',
            country: 'us',
            published_at: '2023-02-15T14:42:10+00:00',
        },
        // {
        //     author: null,
        //     title: 'Why are NHS staff striking and what should patients do?',
        //     description:
        //         'Many NHS staff members are taking part in strikes, in a dispute over pay.',
        //     url: 'https://www.bbc.co.uk/news/health-63561305?at_medium=RSS\u0026at_campaign=KARANGA',
        //     source: 'BBC News - Health',
        //     image: null,
        //     category: 'health',
        //     language: 'en',
        //     country: 'gb',
        //     published_at: '2023-02-24T11:46:29+00:00',
        // },
        // {
        //     author: 'Alisha Haridasani Gupta',
        //     title: 'What to Know About PFAS in Thinx and Other Period Underwear',
        //     description:
        //         'Thinx just settled a lawsuit alleging its products contain harmful chemical compounds, raising further questions about the safety of period products overall.',
        //     url: 'https://www.nytimes.com/2023/01/20/well/pfas-thinx-period-underwear.html',
        //     source: 'The New York Times',
        //     image: 'https://static01.nyt.com/images/2023/01/19/well/Period-Products-PFAS1/Period-Products-PFAS1-moth.jpg',
        //     category: 'health',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-01-20T21:05:41+00:00',
        // },
        // {
        //     author: 'Dani Blum',
        //     title: 'Zero-Calorie Sweetener Possibly Linked to Heart Issues, New Study Suggests',
        //     description:
        //         'Recent findings have sounded alarms among researchers, but experts say artificial sweeteners need more investigation.',
        //     url: 'https://www.nytimes.com/2023/02/28/well/artificial-sweetener-heart-attack-stroke.html',
        //     source: 'The New York Times',
        //     image: 'https://static01.nyt.com/images/2023/02/28/well/28Well-Sugar/28Well-Sugar-moth-v2.jpg',
        //     category: 'health',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-03-01T18:11:43+00:00',
        // },
        // {
        //     author: 'Dani Blum',
        //     title: 'One Side Effect of Ozempic? Less Drinking, Some Say',
        //     description:
        //         'As the diabetes drug gains more attention, a surprising side effect has emerged.',
        //     url: 'https://www.nytimes.com/2023/02/24/well/eat/ozempic-side-effects-alcohol.html',
        //     source: 'The New York Times',
        //     image: 'https://static01.nyt.com/images/2023/02/17/well/17-OZEMPIC-ALCOHOL/17-OZEMPIC-ALCOHOL-moth.jpg',
        //     category: 'health',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-02-24T21:19:15+00:00',
        // },
        // {
        //     author: null,
        //     title: 'EVT Will Save Millions of Lives From Stroke. Eventually.',
        //     description:
        //         'A procedure called EVT is creating radically better outcomes for patients, but only when it\u2019s performed quickly enough \u2014 and that requires the transformation of an entire system of care.',
        //     url: 'https://www.nytimes.com/2023/03/01/magazine/evt-stroke-treatment.html',
        //     source: 'The New York Times',
        //     image: 'https://static01.nyt.com/images/2023/03/05/magazine/05mag-stroke-02/05mag-stroke-02-moth.jpg',
        //     category: 'health',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-03-01T10:00:25+00:00',
        // },
        // {
        //     author: null,
        //     title: 'Why are NHS staff striking and what should patients do?',
        //     description:
        //         'Many NHS staff members are taking part in strikes, in a dispute over pay.',
        //     url: 'https://www.bbc.co.uk/news/health-63561305?at_medium=RSS\u0026at_campaign=KARANGA',
        //     source: 'BBC News - Health',
        //     image: null,
        //     category: 'health',
        //     language: 'en',
        //     country: 'gb',
        //     published_at: '2023-03-05T10:35:07+00:00',
        // },
        // {
        //     author: 'Lisa Sanders, M.D.',
        //     title: 'He Was Sweating Uncontrollably. Was It Male Menopause?',
        //     description:
        //         'His vital signs were normal. He didn\u2019t have a fever. A slew of tests couldn\u2019t find the cause. Then a locker-room conversation between doctors led to the diagnosis.',
        //     url: 'https://www.nytimes.com/2023/03/09/magazine/sweating-seizures-diagnosis.html',
        //     source: 'The New York Times',
        //     image: null,
        //     category: 'health',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-03-09T10:00:10+00:00',
        // },
        // {
        //     author: 'Catherine Pearson',
        //     title: 'Cancer Can Upend Your Sex Life. Here\u2019s How to Get Help.',
        //     description:
        //         'Despite a wave of new research around cancer treatment and sexual health, women say their issues are still being dismissed. Here\u2019s how and where to get help.',
        //     url: 'https://www.nytimes.com/2023/03/10/well/family/sex-women-cancer-treatment.html',
        //     source: 'The New York Times',
        //     image: 'https://static01.nyt.com/images/2023/02/20/well/20Well-Sex-Cancer/20Well-Sex-Cancer-moth.jpg',
        //     category: 'health',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-03-10T10:00:22+00:00',
        // },
        // {
        //     author: 'Alice Callahan',
        //     title: 'Her Doctor Said Her Illness Was All in Her Head. This Scientist Was Determined to Find the Truth.',
        //     description:
        //         'After enduring severe nausea and vomiting in pregnancy, the geneticist Marlena Fejzo made finding the cause of her condition, hyperemesis gravidarum, her life\u2019s work.',
        //     url: 'https://www.nytimes.com/2023/03/14/well/marlena-fejzo-hyperemesis-gravidarum.html',
        //     source: 'The New York Times',
        //     image: 'https://static01.nyt.com/images/2023/03/07/multimedia/00FEJZO-PROFILE2-gqbj/00FEJZO-PROFILE2-gqbj-moth.jpg',
        //     category: 'health',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-03-14T15:08:14+00:00',
        // },
        // {
        //     author: 'Hannah Seo',
        //     title: 'Can Allergies Make You Tired? How to Tell Symptoms Apart',
        //     description:
        //         'Many health conditions, ranging from hay fever to the common cold, can leave us feeling drained. Here\u2019s how to tell what\u2019s causing your fatigue.',
        //     url: 'https://www.nytimes.com/2023/03/14/well/live/allergy-fatigue-symptoms.html',
        //     source: 'The New York Times',
        //     image: 'https://static01.nyt.com/images/2023/03/14/multimedia/14ASKWELL-ALLERGIES-FATIGUE1-jtlc/14ASKWELL-ALLERGIES-FATIGUE1-jtlc-moth.jpg',
        //     category: 'health',
        //     language: 'en',
        //     country: 'us',
        //     published_at: '2023-03-14T13:21:28+00:00',
        // },
    ],
};
